# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "📱 Remi k"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About me"
    href:           "http://remirobert.github.io/about"

  - name:           "resume"
    href:           "/resume/index.html"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
